### ISSUE TITLE
При отправке сообщения в чат не обновляется информация в боковом меню

### ISSUE THREAD

**Issue by DuckLuckBreakout** [vaderoi/InCorp-messenger#14]
![Снимок экрана 2020-12-17 в 01 30 06](https://user-images.githubusercontent.com/49189299/102414334-66e27d00-4007-11eb-99cb-47087681ec3c.png)

**Comment by Tullerpeton** [comment]
Добавил функцию отображения сообщения, написанного клиентом в открытый чат.
