### ISSUE TITLE
Краш при получении ответа на 23 команду

### ISSUE THREAD

**Issue by DuckLuckBreakout** [vaderoi/InCorp-messenger#17]
Если в чате не было последнего сообщения, возвращается пустое боди, в котором клиент пытается найти поля сообщения
![Снимок экрана 2020-12-17 в 13 22 28](https://user-images.githubusercontent.com/49189299/102475442-eb1a1c00-406a-11eb-86e6-54cef584b5f4.png)

**Comment by Tullerpeton** [comment]
Исправил отображение чатов, если в них ещё нет сообщений.
