### ISSUE TITLE
Ошибка в теле запроса о получении сообщений из чата

### ISSUE THREAD

**Issue by DuckLuckBreakout** [vaderoi/InCorp-messenger#7]
Всегда `"lastMessageNum": "0"` и `"chatId": "1"`

**Comment by Tullerpeton** [comment]
Добавил : `"chatId" `- текущий чат, `"lastMessageNum"` - 0

**Comment by DuckLuckBreakout** [comment]
Необходимо добавить обработку ситуации, когда новых сообщений нет

**Comment by Tullerpeton** [comment]
Добавил обработку чата, в котором отсутствуют сообщения пользователей.
