### ISSUE TITLE
Не отображаются данные в сообщениях, которые отправил текущий пользователь

### ISSUE THREAD

**Issue by DuckLuckBreakout** [vaderoi/InCorp-messenger#9]
Не отображаются данные в сообщениях, которые отправил текущий пользователь в текущей сессии
<img width="379" alt="Снимок экрана 2020-12-16 в 22 21 49" src="https://user-images.githubusercontent.com/49189299/102396159-1b22da00-3fed-11eb-88bb-a444c7bb458f.png">

**Comment by Tullerpeton** [comment]
Добавил информация о пользователе, написавшем в открытый чат.
